---
title: ''
author: ''
csl: apa.csl
output:
  pdf_document:
    number_sections: yes
  html_document:
    df_print: paged
  word_document: default
header-includes:
- \usepackage[T1]{fontenc}
- \usepackage{microtype}
- \usepackage[margin=1in]{geometry}
- \usepackage{fancyhdr}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[C]{Online Supplement}
- \fancyfoot[RO,LE]{\thepage}
- \usepackage{booktabs}
- \usepackage{lettrine}
- \usepackage{paralist}
- \usepackage{setspace}\singlespacing
- \usepackage{url}
- \usepackage{parskip}
- \usepackage{color,soul}
- \usepackage{palatino}
- \usepackage{booktabs}
- \usepackage{makecell}
- \usepackage{float}
bibliography: refs_uv3.bib
---

\doublespacing

\begin{center}
\textbf{ \LARGE{Online Supplement: \\Open-source software for mouse-tracking in Qualtrics to measure category competition} }
\vspace{10mm}
\end{center}

\doublespacing

\vspace{10mm}
\begin{center}
\large{ \emph{ Maya B. Mathur and David B. Reichling } } \\
\end{center}

\vspace{10mm}



\setlength{\parskip}{1em}


\singlespacing


\section{Qualtrics instructions to subjects}
\label{sec:instruct}


You will be shown a series of faces, one at a time, and you should decide whether each is a robot or a human by clicking one of the two answer buttons at the top of the window. We are recording the speed and accuracy of your answers, so please answer as quickly and accurately as possible even though some faces may be hard to categorize. To speed up your answer, you should begin moving the cursor very soon after the face is displayed (within 1/2 second), even if you have not yet fully decided which answer you will choose. However, it is important that you do not begin moving the cursor until the face appears on the screen -- the cursor must begin the next question positioned over the Next button, so after clicking "Next", do not move the mouse while you’re waiting for the next face to be displayed.

We understand it can be tricky for you to move the cursor quickly, but not too quickly, on every single question, and we will issue alerts to let you know when the timing isn’t correct. Please don’t be stressed by these alerts; they are just meant to help you improve your timing.

After you click the "Next" button on this page, you will begin a series of 6 practice faces (labeled "Practice") to familiarize yourself with the task. Then you will go directly into the actual task.

This entire task needs to be done in a single sitting, which should take about 3 minutes. Also, you must not use a touchscreen device to complete this task (a physical mouse or trackpad, as on a laptop, is fine). 

\section{Alert messages}

\label{sec:alerts}

\subsection{Started too early}

STARTED TOO EARLY

You moved the cursor off the Next button before the question was fully displayed.

\subsection{Started too late}

STARTED TOO LATE

You waited a little too long to start moving the cursor. To speed up your answer, try to start moving the cursor sooner, even if you are not yet fully decided about your final answer.


\subsection{Took too long}

You took longer than the 5-second total time limit to click an answer.


\subsection{Window too small}

Your browser window is too small. Please make it larger.


